name: digipin_converter
description: "A Dart package for converting between geographical coordinates and India Post's DIGIPINs."
version: 0.1.0
homepage: https://github.com/pk-the-dev/digipin_converter

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
